services:
  postgres:
    image: postgres:16
    container_name: jobtracker-db
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpass
    ports:
      - "5432:5432"
